# Generated by Django 5.2.8 on 2025-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageoffer',
            name='closing_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
