# Generated by Django 6.0 on 2025-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_candidature_status_stageoffer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageoffer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stageoffer',
            name='domain',
            field=models.CharField(blank=True, choices=[('Développement Web', 'Développement Web'), ('Développement Mobile', 'Développement Mobile'), ('Data Science', 'Data Science'), ('Cybersécurité', 'Cybersécurité'), ('DevOps', 'DevOps'), ('IA/Machine Learning', 'IA/Machine Learning'), ('Réseau', 'Réseau'), ('Base de données', 'Base de données'), ('Cloud Computing', 'Cloud Computing'), ('Autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stageoffer',
            name='duration',
            field=models.CharField(blank=True, choices=[('1-3 mois', '1-3 mois'), ('3-6 mois', '3-6 mois'), ('6+ mois', '6+ mois')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stageoffer',
            name='remote',
            field=models.BooleanField(default=False, help_text='Stage en télétravail possible'),
        ),
    ]
